package TasksAndSyncs.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class FutureJoin_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode virtual_getTarget_7034214596260727602(SNode thisNode) {
    return thisNode;
  }
}
