package TasksAndSyncs.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Expression_BehaviorDescriptor;

public class Sync_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public Sync_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TasksAndSyncs.structure.Sync";
  }
}
