package TasksAndSyncs.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class SyncVariable_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public SyncVariable_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TasksAndSyncs.structure.SyncVariable";
  }
}
