package TasksAndSyncs.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class SyncRessourcePlain_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public SyncRessourcePlain_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TasksAndSyncs.structure.SyncRessourcePlain";
  }
}
