package TasksAndSyncs.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Expression_BehaviorDescriptor;
import com.mbeddr.core.expressions.behavior.IGenericDotTarget_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import com.mbeddr.core.expressions.behavior.IGenericDotTarget_Behavior;

public class TaskJoin_BehaviorDescriptor extends Expression_BehaviorDescriptor implements IGenericDotTarget_BehaviorDescriptor {
  public TaskJoin_BehaviorDescriptor() {
  }

  public SNode virtual_getTarget_7034214596260727602(SNode thisNode) {
    return TaskJoin_Behavior.virtual_getTarget_7034214596260727602(thisNode);
  }

  public boolean virtual_isLValue_6118219496712710630(SNode thisNode) {
    return IGenericDotTarget_Behavior.virtual_isLValue_6118219496712710630(thisNode);
  }

  public String virtual_renderReadable_8274105510415878941(SNode thisNode) {
    return IGenericDotTarget_Behavior.virtual_renderReadable_8274105510415878941(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "TasksAndSyncs.structure.TaskJoin";
  }
}
