package TasksAndSyncs.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class Task_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String virtual_getPresentation_1213877396640(SNode thisNode) {
    return "|" + BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(thisNode, "expression", true), "virtual_getPresentation_1213877396640", new Object[]{}) + "|";
  }
}
