package TasksAndSyncs.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class TaskType_Behavior {
  public static void init(SNode thisNode) {
  }

  public static int virtual_getUsedBytes_6941595764870551407(SNode thisNode) {
    return 0;
  }

  public static String virtual_getPresentation_1213877396640(SNode thisNode) {
    return "Task<" + StringUtils.stripEnd(BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(thisNode, "returnType", true), "virtual_getPresentation_1213877396640", new Object[]{}), " \n\r\t") + ">";
  }
}
