package parallelization.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Expression_BehaviorDescriptor;

public class SyncStart_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public SyncStart_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "parallelization.structure.SyncStart";
  }
}
