package TasksAndSyncs.generator.util;

/*Generated by MPS */


public class NameGenerator {
  public static String getGenericTaskModuleName() {
    return "GenericDeclarations";
  }



  public static String getTaskStructName() {
    return "Task";
  }



  public static String getFutureStructName() {
    return "Future";
  }



  public static String getFutureFunctionName() {
    return "runTaskAndGetFuture";
  }



  public static String getFutureJoinFunctionName() {
    return "joinFuture";
  }



  public static String getFutureResultFunctionName() {
    return "getFutureResult";
  }
}
