package TasksAndSyncs.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import jetbrains.mps.typesystem.inference.EquationInfo;
import jetbrains.mps.smodel.SModelUtil_new;

public class typeof_Task_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_Task_InferenceRule() {
  }

  public void applyRule(final SNode task, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      final SNode expressionType = typeCheckingContext.typeOf(SLinkOperations.getTarget(task, "expression", true), "r:daf934de-3466-4fa8-a227-270fedb7e2f2(TasksAndSyncs.typesystem)", "482600553438622935", true);
      typeCheckingContext.whenConcrete(expressionType, new Runnable() {
        public void run() {
          SNode taskType = SConceptOperations.createNewNode("TasksAndSyncs.structure.TaskType", null);

          if (SNodeOperations.isInstanceOf(typeCheckingContext.getExpandedNode(expressionType), "com.mbeddr.core.expressions.structure.VoidType")) {
            SLinkOperations.setTarget(taskType, "returnType", SNodeOperations.cast(typeCheckingContext.getExpandedNode(expressionType), "com.mbeddr.core.expressions.structure.Type"), true);
          } else {
            SLinkOperations.setTarget(taskType, "returnType", new _FunctionTypes._return_P0_E0<SNode>() {
              public SNode invoke() {
                final SNode node_482600553438935901 = new _FunctionTypes._return_P0_E0<SNode>() {
                  public SNode invoke() {
                    SNode res = typeCheckingContext.getExpandedNode(expressionType);
                    return res;
                  }
                }.invoke();
                SNode node_482600553438935183 = new _FunctionTypes._return_P0_E0<SNode>() {
                  public SNode invoke() {
                    SNode res = SConceptOperations.createNewNode("com.mbeddr.core.pointers.structure.PointerType", null);
                    SLinkOperations.setTarget(res, "baseType", node_482600553438935901, true);
                    return res;
                  }
                }.invoke();
                return node_482600553438935183;
              }
            }.invoke(), true);
          }

          {
            SNode _nodeToCheck_1029348928467 = task;
            EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:daf934de-3466-4fa8-a227-270fedb7e2f2(TasksAndSyncs.typesystem)", "1304213873206865411", 0, null);
            typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:daf934de-3466-4fa8-a227-270fedb7e2f2(TasksAndSyncs.typesystem)", "1304213873206861757", true), (SNode) taskType, _info_12389875345);
          }
        }
      }, "r:daf934de-3466-4fa8-a227-270fedb7e2f2(TasksAndSyncs.typesystem)", "482600553438622806", false, false);
    }
  }

  public String getApplicableConceptFQName() {
    return "TasksAndSyncs.structure.Task";
  }

  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    {
      boolean b = SModelUtil_new.isAssignableConcept(argument.getConcept().getQualifiedName(), this.getApplicableConceptFQName());
      return new IsApplicableStatus(b, null);
    }
  }

  public boolean overrides() {
    return false;
  }
}
